serial:
  port: /dev/tty.usbmodem000001
mqtt:
  broker: api.xively.com
  port: 1883
  username: <xively_api_key_here>
sensors:
  R1:
    RIVR:
      mqtt_endpoint: 
      publish_id: riverheight
      latitude: 51.772222
      longitude: -1.289722
    
  T5:
    TMPA:
      mqtt_endpoint: 
      publish_id: temperature
      latitude: 51.772222
      longitude: -1.289722
    
